Major and Minor updates to GDL (#206)
* Adding files to create a docker image

* - arbitrary band support
- minor refactor

* - url assets support added specifically for inference
- minor fixes and changes

* - support for arbitrary number of bands

* - fixed! support for arbitrary number of bands

* - cuda device fix

* - added vectorisation

* - added module collections
- removed redundant log_artifact function

* - added new sample creation script

* - fixed tst set data allocation

* - changes to inference.py

* - minor fix for debugging

* - minor fix

* - fix num_classes/class weight mismatch

* - added sample creation by sensorID filter

* - minor fix, get_num_samples function

* - stratification trial fix

* - debug print statements added

* removed debug print statements

* - hyperopt template modified
- dice loss fixed
- added weight to duo loss

* - minor change, file location

* - commented to solve file permission errors

* - target_size modified to solve out of memory issues

* - temporary template added for training on HPC
- customizable file paths added for hyperopt assets

* - minor fix

* - temporary fix for
TypeError: load_state_dict() got an unexpected keyword argument 'strict'

* - updated

* - added pretrained weights param Hpc, local

* - model space added

* - minor fix to input tensor mismatch

* minor fixes: addressing code review
- losses: __init__.py
- utils: geoutils.py, visualization.py
- gdl_hyperopt_HPC removed
- README.md correction
- train_segmentation.py: space indent fixes, checkpoint path logged on mlflow

* fixes and new features:
- models: model_choice.py #fixed cuda runtime error
- utils: augmentation.py #logging info statement removed, visualization.py #indentation fix
- inference.py # new memory management features added, smoothing func improved
- train_segmentation.py: space indent fixes, cuda runtime error fixes

* - fix: param dict passed explicitly to avoid global calls.

* - fix, clipped raster

* - minor fixes: removed dask, added time checks

* Fixed sugggested changes by reviewers
- gdl_hyperopt_template.py
- inference.py

Co-authored-by: Yves Choquette <yves.choquette@canada.ca>
Co-authored-by: valhassan <victor.alhassan@canada.ca>